export const references = [
  {
    id: 814,
    title: "ETKINIZ III: Support to Monitoring the Human Rights Situation in Türkiye",
    sector: "Governance & Human Development",
    country: "Turkey",
    year: 2024,
  },
  {
    id: 813,
    title: "Technical Assistance Services for the Facilitation Engineering of the ADAPT Program",
    sector: "Governance & Human Development",
    country: "Tunisia",
    year: 2024,
  },
  {
    id: 812,
    title: "Technical Assistance for the 11th EDF Intra-ACP Natural Disaster Risk Reduction Program",
    sector: "Environment & Climate Change",
    country: "Africa",
    year: 2023,
  },
  {
    id: 811,
    title: "Pre-feasibility study of a sustainable national digital agriculture platform",
    sector: "Agriculture & Rural Development",
    country: "Morocco",
    year: 2023,
  },
  {
    id: 810,
    title: "Support for inclusive local development and sustainable food systems",
    sector: "Agriculture & Rural Development",
    country: "Algeria",
    year: 2022,
  },
  {
    id: 809,
    title: "Technical support for water resources management and irrigation planning",
    sector: "Water & Infrastructure",
    country: "Tunisia",
    year: 2022,
  },
  {
    id: 808,
    title: "Capacity building program for rural cooperatives and local producers",
    sector: "Agriculture & Rural Development",
    country: "Senegal",
    year: 2021,
  },
  {
    id: 807,
    title: "Feasibility study for climate-smart irrigation systems",
    sector: "Water & Infrastructure",
    country: "Egypt",
    year: 2021,
  },
  {
    id: 806,
    title: "Technical assistance for food security and agricultural value chains",
    sector: "Agriculture & Rural Development",
    country: "Jordan",
    year: 2020,
  },
  {
    id: 805,
    title: "Environmental and social impact assessment for rural infrastructure",
    sector: "Environment & Climate Change",
    country: "Lebanon",
    year: 2020,
  },
  {
    id: 804,
    title: "Support to public sector reform and institutional development",
    sector: "Governance & Human Development",
    country: "Morocco",
    year: 2019,
  },
  {
    id: 803,
    title: "Development of regional agricultural investment plans",
    sector: "Agriculture & Rural Development",
    country: "Tunisia",
    year: 2019,
  },
  {
    id: 802,
    title: "Technical assistance for sustainable land management",
    sector: "Environment & Climate Change",
    country: "Ethiopia",
    year: 2018,
  },
  {
    id: 801,
    title: "Support for integrated water resources planning",
    sector: "Water & Infrastructure",
    country: "Kenya",
    year: 2018,
  },
  {
    id: 800,
    title: "Rural employment and entrepreneurship support program",
    sector: "Governance & Human Development",
    country: "Algeria",
    year: 2017,
  },
  {
    id: 799,
    title: "Agricultural market systems and value chain analysis",
    sector: "Agriculture & Rural Development",
    country: "Ghana",
    year: 2017,
  },
  {
    id: 798,
    title: "Climate adaptation strategy for vulnerable rural territories",
    sector: "Environment & Climate Change",
    country: "Mali",
    year: 2016,
  },
  {
    id: 797,
    title: "Technical support for infrastructure project preparation",
    sector: "Water & Infrastructure",
    country: "Rwanda",
    year: 2016,
  },
];